-- [nfnl] Compiled from lua/lsp.fnl by https://github.com/Olical/nfnl, do not edit.
local config = require("lspconfig")
local mason = require("mason")
local masonLspconfig = require("mason-lspconfig")
local fidget = require("fidget")
local lspsaga = require("lspsaga")
local watchfiles = require("vim.lsp._watchfiles")
local dap = require("dap")
local dap_projects = require("nvim-dap-projects")
local nvim_dap_virtual_text = require("nvim-dap-virtual-text")
local dap_ui = require("dapui")
local neodev = require("neodev")
mason.setup()
masonLspconfig.setup()
config.tsserver.setup({})
config.omnisharp.setup({})
config.gdscript.setup({cmd = {"ncat", "localhost", "6005"}, flags = {debounce_text_changes = 500}})
config.rust_analyzer.setup({})
config.lua_ls.setup({})
fidget.setup({})
lspsaga.setup({ui = {border = "none", winblend = 50}, symbol_in_winbar = {enable = false}, lightbulb = {enable = false}, outline = {win_position = "float", close_after_jump = true}})
local function _1_(_, _0, _1)
  return true
end
watchfiles["_watchfunc"] = _1_
dap.defaults.fallback["exception_breakpoints"] = {"rust_panic"}
dap_projects.search_project_config()
nvim_dap_virtual_text.setup()
dap_ui.setup()
vim.fn.sign_define("DapBreakpoint", {text = "\240\159\148\180", texthl = "DapBreakpointSymbol", linehl = "DapBreakpoint", numhl = "DapBreakpoint"})
vim.diagnostic.config({update_in_insert = false})
return neodev.setup()
